# Use uma imagem base com Java 21
FROM eclipse-temurin:21-jdk-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos do projeto para o contêiner
COPY . /app

# Exponha a porta que a aplicação Spring Boot usa (geralmente 8080)
EXPOSE 8080

# Comando para executar a aplicação Spring Boot
CMD ["./mvnw", "spring-boot:run"]