# Etapa de build com OpenJDK 21 e Maven
FROM openjdk:21-jdk AS build

WORKDIR /app

COPY . /app

RUN chmod +x ./mvnw && ./mvnw clean dependency:list install

# Etapa final: executa a aplicação
FROM openjdk:21-jdk

WORKDIR /app

COPY --from=build /app /app

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]