# Etapa de build com OpenJDK 21 e Maven
FROM openjdk:21-jdk AS build

WORKDIR /app

COPY . /app

RUN echo "--- Verificando versões ---" && java -version && mvn --version
RUN echo "--- Verificando variáveis de ambiente ---" && env
RUN echo "--- Verificando compilador Java ---" && javac -version
RUN echo "--- Executando build com stack trace completo ---" && chmod +x ./mvnw && ./mvnw -e clean install -DskipTests

# Etapa final: executa a aplicação
FROM openjdk:21-jdk

WORKDIR /app

COPY --from=build /app /app

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]